#!/bin/bash
ACTION="$1"
shift
PACKAGE_LIST="$@"

LLV="$(which lliurex-version)"
DOCKER="$(which docker)"

# Epic-gtk bug !!! Doesn't support echoes out of predefined sections
#if [ -z "$DOCKER" ]; then
#	echo "ERROR: docker binary not available!!!"
#fi

export TEXTDOMAIN="zero-lliurex-smart"
str1=$(gettext "Unable to install, this installer is incompatible with")
str2=$(gettext "Please remove all packages from official installer first")
stra=$(gettext "official smart installer!")
strb=$(gettext "smart-product-drivers from official smart installer!")
strc=$(gettext "nwfermi-module-host from official smart installer!")
codename=$(lsb_release -sc)
vardir="/var/lib/n4d/variables"
if [ "x$codename" = "xbionic" ]; then
        vardir="${vardir}-dir"
fi

case $ACTION in
	preInstall)
		echo "preInstall..."
		statusA=$(jq '.ZEROCENTER.value."zero-lliurex-smart".state' ${vardir}/ZEROCENTER)
		statusB=$(dpkg-query -W -f '${Status}' smart-product-drivers 2>/dev/null)
		statusC=$(dpkg-query -W -f '${Status}' nwfermi-module-host 2>/dev/null)
		ret=0
		if [ "${statusA}" == "1" ]; then
				kdialog --error "${str1} ${stra}\n${str2}"
				ret=1
		fi
		if [ $ret -eq 0 -a "${statusB}" == 'install ok installed' ]; then
				kdialog --error "${str1} ${strb}\n${str2}"
				ret=1
		fi
		if [ $ret -eq 0 -a "${statusC}" == 'install ok installed' ]; then
				kdialog --error "${str1} ${strc}\n${str2}"
				ret=1
		fi
		exit $ret
	;;
	postInstall)
		skip_download=0
		if [ -n "$LLV" -a -x "$LLV" ]; then
			eval export $(lliurex-version -e -a)
			if [ -n "$UNKNOWN" -a "x$UNKNOWN" = "yes" ]; then
				if [ "x$LTSP" = "yes" -a "x$USERNAME" = "root" ]; then
					skip_download=1
				fi
			fi
		else
			echo "Warning: lliurex-version not found!!! Skip detection will not be available!!!"
		fi
		if [ "x$skip_download" != "x1" ]; then
			echo "Downloading docker image, please wait a moment..."

			docker pull lliurex/lliurex-smart
			check_download=$(docker images lliurex/lliurex-smart -q)
			if [ "$check_download" == " " ]; then
				exit 1
			fi
		else
			echo "Chroot environment detected, skipping download image, manual download will be needed after this install"
		fi
	;;
	remove)
		lliurex-smart -purge || true
		apt-get -y remove ${PACKAGE_LIST}
	;;
esac
exit 0

